Update poweroff

diff --git a/poweroff b/poweroff
--- a/poweroff
+++ b/poweroff
@@ -1,3 +1,3 @@
 #!/bin/sh
 echo "Powering off"
-[[ "$(/busybox whoami)" == "root" ]] && /busybox sync; /busybox poweroff -f now ||  echo "Cannot power off as a normal user!"
+/busybox sync; /busybox poweroff -f now ||  echo "Cannot power off as a normal user!"
