Update reboot

diff --git a/reboot b/reboot
--- a/reboot
+++ b/reboot
@@ -1,3 +1,3 @@
 #!/bin/sh
 echo "Rebooting"
-[[ "$(/busybox whoami)" == "root" ]] && /busybox sync; /busybox reboot -f now ||  echo "Cannot reboot off as a normal user!"
+/busybox sync; /busybox reboot -f now ||  echo "Cannot reboot off as a normal user!"
